### ISSUE TITLE
搜索框无法切换到中文输入

### ISSUE THREAD

**Issue by lowy** [fengleyl/NetEase#1]
在搜索框打快捷键Ctrl_space无法调出fcitx输入法 只能用便签粘贴复制

**Comment by hrfyl** [comment]
你没有安装fictx-qt5模块，另外网易API换了，软件目前无法使用

**Comment by lowy** [comment]
然而我的还能用 中文输入的问题已经解决了 可能是因为我的QT5是以前本地编译安装的缘故 现在更新了官源 重新编译了软件就好了  然而蛋疼的是我把帐号给忘了.......

**Comment by hrfyl** [comment]
重写了一下项目 https://github.com/fengleyl/NetEaseMusic
可以看看
